### ISSUE TITLE
Display basic info about dumped files

### ISSUE THREAD

**Issue by lifehackerhansol** [DS-Homebrew/dsbf_dump#2]
A CRC32 function on 16KB files should not be too taxing on the poor DS-mode hardware. Firmware shouldn't be hash checked as the contents of firmware changes with Wi-Fi settings.

This isn't strictly required to have, but certainly a nice to have.

**Comment by spellboundtriangle** [comment]
> Firmware shouldn't be hash checked as the contents of firmware changes with Wi-Fi settings.

Would it be worthwhile to instead show information from the firmware? Such as built timestamp (and their corresponding "version number"), console type, etc https://problemkaputt.de/gbatek-ds-firmware-header.htm
Which I guess would be outside the realm of the purpose of file verification, but

**Comment by lifehackerhansol** [comment]
Now that we have stable firmware reading, it's an option. 

The BIOS checking will be implemented first, though, as I consider that higher priority. If I have the screen real estate I'll also add a few firmware information as well. I already check the console type as well as the MAC address, so maybe it's good to explicitly display that.

**Comment by lifehackerhansol** [comment]
BIOS checksum was added.
